[package]
name = "ai-zero-trust-threat-system"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tch = "0.5.0"
polars = "0.20.0"
log = "0.4"
config = "0.11"
