version: '3.8'

services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181  # Port Zookeeper listens on
      ZOOKEEPER_TICK_TIME: 2000    # Zookeeper tick time in milliseconds
      ZOOKEEPER_SYNC_LIMIT: 2      # Sync limit between Zookeeper nodes
    networks:
      - kafka-net

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093, OUTSIDE://localhost:9092  # Advertised listeners for external and internal access
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT, OUTSIDE:PLAINTEXT
      KAFKA_LISTENER_NAMES: INSIDE, OUTSIDE
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093, OUTSIDE://0.0.0.0:9092  # Listeners for internal and external communication
      KAFKA_LISTENER_PROTOCOL_MAP: INSIDE:PLAINTEXT, OUTSIDE:PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181  # Connect Kafka to Zookeeper
      KAFKA_ADVERTISED_LISTENER: OUTSIDE://localhost:9092  # Advertise external listener
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
    networks:
      - kafka-net
    depends_on:
      - zookeeper

networks:
  kafka-net:
    driver: bridge
