[package]
name = "wasm-threat-processor"
version = "0.1.0"
edition = "2018"  # Use Rust 2018 edition for compatibility

[dependencies]
wasm-bindgen = "0.2"  # Dependency for WebAssembly bindings

# Optional dependencies (to support other WASM-related functionality):
console_error_panic_hook = "0.1"  # Helps in debugging by logging panic messages to the console

[lib]
crate-type = ["cdylib"]  # Tells Cargo to compile to WebAssembly (cdylib type)

[profile.release]
# Optimization settings for release builds
opt-level = "z"  # Optimize for size, useful for WASM

[package.metadata.wasm-opt]
enabled = true  # Enables wasm-opt to optimize the generated WASM code
